/*
 * Copyright (c) 2021 Michael Davidsaver  All rights reserved.
 *
 * The license and distribution terms for this file may be
 * found in the file LICENSE in this distribution or at
 * http://www.rtems.org/license/LICENSE.
 */
#ifndef LIBBSP_ARM_MARBLE_H
#define LIBBSP_ARM_MARBLE_H

#include <bsp.h>

#ifndef MARBLE_MINI
#error Only for MARBLE_MINI
#endif

/* Initialization support */

int marble_bsp_init(void);

/* Application GPIO pin definitions */

#define MARBLE_PROG_B LPC24XX_IO_INDEX_BY_PORT(0, 4)
#define MARBLE_PROG_B_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_FPGA_DONE LPC24XX_IO_INDEX_BY_PORT(0, 7)
#define MARBLE_FPGA_DONE_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC1_FUSE LPC24XX_IO_INDEX_BY_PORT(0, 23)
#define MARBLE_FMC1_FUSE_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC2_FUSE LPC24XX_IO_INDEX_BY_PORT(0, 24)
#define MARBLE_FMC2_FUSE_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_OVER_TEMP LPC24XX_IO_INDEX_BY_PORT(0, 29)
#define MARBLE_OVER_TEMP_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_AT_DET LPC24XX_IO_INDEX_BY_PORT(1, 0)
#define MARBLE_AT_DET_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_EN_FMC1_P12V LPC24XX_IO_INDEX_BY_PORT(1, 27)
#define MARBLE_EN_FMC1_P12V_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_EN_PSU_CH LPC24XX_IO_INDEX_BY_PORT(1, 31)
#define MARBLE_EN_PSU_CH_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_Pmod3_5 LPC24XX_IO_INDEX_BY_PORT(2, 2)
#define MARBLE_Pmod3_5_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_SDRAM_PGOOD LPC24XX_IO_INDEX_BY_PORT(2, 4)
#define MARBLE_SDRAM_PGOOD_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_EINT1 LPC24XX_IO_INDEX_BY_PORT(2, 11)
#define MARBLE_EINT1_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_BOOT_MODE0 LPC24XX_IO_INDEX_BY_PORT(2, 16)
#define MARBLE_BOOT_MODE0_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_BOOT_MODE1 LPC24XX_IO_INDEX_BY_PORT(2, 17)
#define MARBLE_BOOT_MODE1_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_BOOT_MODE2 LPC24XX_IO_INDEX_BY_PORT(2, 18)
#define MARBLE_BOOT_MODE2_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_AMC_GA0 LPC24XX_IO_INDEX_BY_PORT(3, 0)
#define MARBLE_AMC_GA0_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_AMC_GA1 LPC24XX_IO_INDEX_BY_PORT(3, 1)
#define MARBLE_AMC_GA1_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_AMC_GA2 LPC24XX_IO_INDEX_BY_PORT(3, 2)
#define MARBLE_AMC_GA2_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC1_PRSNT_Override LPC24XX_IO_INDEX_BY_PORT(3, 6)
#define MARBLE_FMC1_PRSNT_Override_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC2_PRSNT_Override LPC24XX_IO_INDEX_BY_PORT(3, 7)
#define MARBLE_FMC2_PRSNT_Override_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC1_PG_C2M LPC24XX_IO_INDEX_BY_PORT(3, 10)
#define MARBLE_FMC1_PG_C2M_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC2_PG_C2M LPC24XX_IO_INDEX_BY_PORT(3, 11)
#define MARBLE_FMC2_PG_C2M_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_HW_ID0 LPC24XX_IO_INDEX_BY_PORT(3, 23)
#define MARBLE_HW_ID0_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_HW_ID1 LPC24XX_IO_INDEX_BY_PORT(3, 24)
#define MARBLE_HW_ID1_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_HW_ID2 LPC24XX_IO_INDEX_BY_PORT(3, 25)
#define MARBLE_HW_ID2_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_HW_ID3 LPC24XX_IO_INDEX_BY_PORT(3, 26)
#define MARBLE_HW_ID3_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC_TRST LPC24XX_IO_INDEX_BY_PORT(4, 7)
#define MARBLE_FMC_TRST_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_AMC_En LPC24XX_IO_INDEX_BY_PORT(4, 8)
#define MARBLE_AMC_En_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_FPGA_RESETn LPC24XX_IO_INDEX_BY_PORT(4, 9)
#define MARBLE_FPGA_RESETn_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_SW LPC24XX_IO_INDEX_BY_PORT(4, 11)
#define MARBLE_SW_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC_TDO LPC24XX_IO_INDEX_BY_PORT(4, 17)
#define MARBLE_FMC_TDO_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_FMC_TMS LPC24XX_IO_INDEX_BY_PORT(4, 18)
#define MARBLE_FMC_TMS_SETUP LPC24XX_GPIO_OUTPUT

#define MARBLE_FMC_TDI LPC24XX_IO_INDEX_BY_PORT(4, 19)
#define MARBLE_FMC_TDI_SETUP LPC24XX_GPIO_INPUT

#define MARBLE_FMC_TCK LPC24XX_IO_INDEX_BY_PORT(4, 27)
#define MARBLE_FMC_TCK_SETUP LPC24XX_GPIO_OUTPUT

#define marble_gpio_read(NAME) lpc24xx_gpio_get(MARBLE_ ## NAME, VAL)
#define marble_gpio_write(NAME, VAL) lpc24xx_gpio_write(MARBLE_ ## NAME, VAL)


#endif // LIBBSP_ARM_MARBLE_H
